services:
  nginx:
    build: ./nginx
    ports:
      - 3331:80
    depends_on:
      - web
  traefik:
    image: traefik
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./traefik/traefik.yml:/etc/traefik/traefik.yml:ro
      - ./traefik/acme:/etc/traefik/acme
    ports:
      - "3332:80"
      - "3333:443"
      - "3334:8080"
  web:
    build: .
    depends_on:
      - pg
    env_file:
      - web_variables.env
    ports:
      - "3330:5000"
    labels:
      - "traefik.enable=true"
      - "traefik.frontend.rule=Host:web-docker.localhost"
    environment:
      - FLASK_ENV
      - POSTGRES_PASSWORD
      - DATABASE
      - SCOPUS_API_KEY
    volumes:
      - ./app:/mis2018/app
      - ./warehouse:/mis2018/warehouse
      - ./migrations:/mis2018/migrations
  pg:
    image: postgres:11
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=mis2018
    volumes:
      - misdata:/var/lib/postgresql/data
    ports:
      - "3335:5432"

volumes:
  misdata:
